# Generated by Django 4.2.4 on 2024-01-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
