# Generated by Django 4.2.4 on 2024-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_googleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='readDate',
            field=models.DateField(null=True),
        ),
    ]
