# Generated by Django 4.2.4 on 2024-01-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
